Jan 16, 2024 10:31:27 PM src.io.LoggerDeusto log
SEVERE: No se pudo conectar con la base de datos: path to ' /Users/jonmendizabal/git/Proyecto-Concesionario-de-Coches-Final/ProyectoConcesionariofile:/Users/jonmendizabal/git/Proyecto-Concesionario-de-Coches-Final/ProyectoConcesionario/bin/resources/db/database.sqlite': '/Users/jonmendizabal/git/Proyecto-Concesionario-de-Coches-Final/ProyectoConcesionario/ ' does not exist
