Jan 16, 2024 10:27:47 PM src.io.LoggerDeusto log
SEVERE: No se pudo conectar con la base de datos: path to ' file:/Users/jonmendizabal/git/Proyecto-Concesionario-de-Coches-Final/ProyectoConcesionario/bin/resources/db/database.sqlite': '/Users/jonmendizabal/git/Proyecto-Concesionario-de-Coches-Final/ProyectoConcesionario/ file:' does not exist
